### ISSUE TITLE
MEP v1.30.4

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#2262]
- Vérifier les saisies en PROD avec cette requête : 
```
select * from mission_actions where (gear_infractions <> '[]' or species_infractions <> '[]') and id > 0;
```
Car les saisies des engins et espèces ne seront plus dans la colonne infractions mais dans un nouvelle colonne, et il n'y a pas de migration actuellement.

- Rajouter un crontab
```
*/5 * * * * docker restart $(docker ps | grep unhealthy | cut -c -12) 2>/dev/null
```

- Rajouter dans le `docker-compose` de prod en dessous de `restart: always` :
```
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8880/api/v1/healthcheck || exit 1"
      interval: 20s
      timeout: 5s
      retries: 3
```
