### ISSUE TITLE
MEP v1.52.1

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3198]
Ajouter dans le `.monitorfish`:
```
export MONITORFISH_ENV=prod
```

Dans le docker-compose, remplacer le volume :
```
volumes:
  db-data:
    driver: local
  geoserver-data:
    driver: local
```

Et l'image db : 
```
services:
  db:
    image: timescale/timescaledb-postgis:1.7.4-pg11
```
